language: php
 
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false
addons:
  apt:
    packages:
      - openjdk-8-jre-headless

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
